name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas

    - name: Initialize SQLite database
      run: |
        sudo apt-get install sqlite3
        sqlite3 inferences.sqlite < evaluation_runs.sql

    - name: Run neural-results-chart.py
      run: python neural-results-chart.py --input neural-results.csv --output neural-results.png
