name: Validation Run Trigger

on:
  push:
    paths:
      - 'evaluation_runs.sql'
      - 'inferences.sql'      
      - 'charts.py'
      - '.github/workflows/validation_run_trigger.yaml'
  pull_request:
    paths:
      - 'evaluation_runs.sql'
      - 'inferences.sql'            
      - 'charts.py'
      - '.github/workflows/validation_run_trigger.yaml'

jobs:
  make_evaluation_charts:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python3 Pandas
      run: sudo apt-get install -y python3-pandas

    - name: Restore evaluation runs
      run: sqlite3 inferences.sqlite < evaluation_runs.sql

    - name: Restore inferences
      run: sqlite3 inferences.sqlite < inferences.sql      
     
    - name: Run charts.py
      run: python charts.py

    - name: Run neural-results-chart.py
      run: python neural-results-chart.py --input neural-results.csv --output neural-results.png
      
    - name: Commit and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add total_loss_vs_time.png
        git add model_node_count_vs_time.png
        git add average_depth_vs_time.png
        git add average_in_region_hits_vs_time.png
        git add total_loss_vs_model_size.png
        git add total_loss_vs_model_size_with_ensemble.png
        git add noun_loss_vs_model_size.png
        git add noun_loss_vs_model_size_with_ensemble.png
        git add noun_loss_vs_time.png
        git add neural-results.png 
	git add  plain_models_loss_vs_size.png
        git commit -m "Add generated images [skip ci]" || echo "No changes to commit"
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
