name: Validation Run Trigger

on:
  push:
    paths:
      - 'validation_runs.sql'
      - 'charts.py'
      - '.github/workflows/validation_run_trigger.yaml'
      - 'charts.py'
  pull_request:
    paths:
      - 'validation_runs.sql'
      - '.github/workflows/validation_run_trigger.yaml'

jobs:
  run_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Python3 Pandas
      run: sudo apt-get install -y python3-pandas

    - name: Execute SQL script
      run: sqlite3 validation.sqlite < validation_runs.sql
    - name: Run charts.py
      run: python charts.py
    - name: Commit and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add total_loss_vs_time.png
        git add model_node_count_vs_time.png
        git add average_depth_vs_time.png
        git add average_in_region_hits_vs_time.png
        git add total_loss_vs_model_size.png
        git commit -m "Add generated images [skip ci]" || echo "No changes to commit"
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
